<a href="https://colab.research.google.com/github/MustafaKhan670093/ESC180-Intro-To-Computer-Programming/blob/master/Lab%205%20Submission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 5: Lists And Loops**

More information about this lab can be found [here](https://nbviewer.jupyter.org/github/guerzh/esc180lab/blob/master/Lab5.ipynb).

## **Problem 1**

Write a function with the signature `def list1_start_with_list2(list1, list2)`, which returns True iff `list1` is at least as long as `list2`, and the first `len(list2)` elements of `list1` are the same as `list2`. Note: `len(lis)` is the length of the list `lis`, i.e., the number of elements in `lis`.

First write the function without using slicing (“slicing” means saying things like `list1[2:5]`), and using a loop.

In [1]:
def list1_start_with_list2(list1, list2):
  if len(list1) == len(list2):
    for i in range(len(list2)):
      if list1[i] == list2[i]:
        pass
      else:
        return False
    return True
  else:
    return False
  
      
#Test - Same Lists
L1 = [1, 2, 3, 4, 5, 6]
L2 = [1, 2, 3, 4, 5, 6]
print(list1_start_with_list2(L1, L2))

#Test - Different Lists
L3 = [1, 2, 3, 4, 5, 6]
L4 = [1, 2, 3, 4, 5, 6, 7]
print(list1_start_with_list2(L3, L4))

True
False


## **Problem 2**

Write a function with the signature `def match_pattern(list1, list2)` which returns `True` iff the pattern `list2` appears in `list1`. In other words, we return `True` iff there is an `i` such that `0 ≤ i ≤ len(list1)-len(list2)` and
```
list1[i] = list2[0]
list1[i + 1] =list2[1]
    .
    .
    .
list1[i + len(list2) – 1] = list2[-1]
```



For example, if `list1` is `[4, 10, 2, 3, 50, 100]` and `list2` is `[2, 3, 50]`, `match_pattern(list1, list2)` returns `True` since the pattern `[2, 3, 50] `appears in `list1`.

In [2]:
def match_pattern(list1, list2):
  iterate = 0
  for i in range(len(list1)):
    if iterate < len(list2):
      if list2[iterate] == list1[i]:
        iterate += 1 
      else:
        return False
  return True

#Test - Pattern Exists
L1 = [1, 2, 3, 4, 5]
L2 = [1, 2]
print(match_pattern(L1, L2))

#Test - Pattern Does Not Exist
L3 = [1, 2, 3, 4, 5]
L4 = [1, 2, 8, 9]
print(match_pattern(L3, L4))


True
False


## **Problem 3**

Write a function with the signature `def repeats(list0)`, which returns `True` iff `list0` contains at least two adjacent elements with the same value.

In [3]:
def repeats(list0):
  count = 0
  for i in range(len(list0)):
    if count >= 2:
      return True
    if i < len(list0)-2:
      if list0[i] == list0[i+1]:
        count += 1
  return False


#Tests - At Least 2 Repeats Exist
L1 = [1, 1, 2, 3, 4, 5, 6, 6, 7]
print(repeats(L1))

#Tests - At Least 2 Repeats Don't Exist
L2 = [1, 2, 3, 4, 5, 6, 7]
print(repeats(L2))

#Tests - At Least 2 Repeats Don't Exist
L3 = [1, 2, 3, 4, 5, 6, 6, 7]
print(repeats(L3))

True
False
False


## **Problem 4**

In Python, you can use a list of lists to store a matrix, with each inner list representing a row. (For example: `M = [[5, 6, 7], [0, -3, 5]]`)

### **Problem 4(a)**

Write a function with the signature `def print_matrix_dim(M)` which accepts a matrix M in the format above, and prints the matrix dimensions. For example, `print_matrix_dim([[1,2],[3,4],[5,6] ])` should print 3x2.

In [4]:
def print_matrix_dim(M):
  rows = len(M)
  columns = len(M[0])
  print(str(rows) + "x" + str(columns))

M = [[5, 6, 7], [0, -3, 5]]
K = [[100, 200, 300]]

print_matrix_dim(M)
print_matrix_dim(K)

2x3
1x3


### **Problem 4(b)**

Write a function with the signature `def mult_M_v(M, v)` which returns the product `Mv` of a matrix `M` and a vector `v`. Vectors are stored as lists of floats.

To write this function, you will need to create a new vector. Here are two ways to create a new vector (stored as a list) with 10 zeros in it:
```
ten_zeros1 = [0]*10

ten_zeros2 = []
for i in range(10):
  ten_zeros2.append(0)
```




In [5]:
###### Helper Functions ######

import numpy as np

def zeroes(height, width):
  '''Create a matrix of zeroes.'''
  zero_matrix = np.zeros((height, width))
  return zero_matrix

def transpose(M):
  '''Transpose a matrix.'''
  result = [[M[j][i] for j in range(len(M))] for i in range(len(M[0]))]
  return result

def dotproduct(vectora, vectorb):
  '''Return the dot product of two vectors.'''
  # variable for accumulating the sum
  result = 0
  
  # Using a for loop to multiply the two vectors
  # element by element. Accumulate the sum in the result variable
  count = 0
  for i in vectora:
      result = result + i*vectorb[count]
      count+=1
  return result

##############################

def mult_M_v(M, v):
  M_h = len(M)
  M_w = len(M[0])
  v_w = len(v)
  if M_w != v_w:
    print("Vector-matrix product not possible.")
    return;

  vector_matrix_multiply = []

  for i in M:
    vector_matrix_multiply.append(dotproduct(i, v))
    
  return vector_matrix_multiply

### **Test Code For Vector-Matrix Products**


In [6]:
#Test Code - Vector-Matrix Product Working
# 3x3 matrix
print("Test 1")
A = [[12,7, 3],
    [4 ,5, 6],
    [7, 8, 9]]

B = [5,8,1]

print(mult_M_v(A, B))
print(" ")

#Test Code - Vector-Matrix Product Undefined
print("Test 2")
A = [[12,7, 3],
    [4 ,5, 6],
    [7, 8, 9]]

B = [5,8,1, 4]

print(mult_M_v(A, B))

Test 1
[119, 66, 108]
 
Test 2
Vector-matrix product not possible.
None


## **Problem 4(c) (Challenge)**

Write a Python function to perform matrix multiplication.

In [7]:
def matrix_mult(self, other):
  """Perform matrix multiplication."""
  #Check if matrix multiplication is not possible
  self_h = len(self)
  self_w = len(self[0])
  other_h = len(other)
  other_w = len(other[0])

  if self_w != other_h :
      print("Matrices cannot be multiplied.")
      return;
  
  matrixMultiply = zeroes(self_h, other_w)

  # iterate through rows of M1
  for i in range(len(self)):
    # iterate through columns of M2
    for j in range(len(other[0])):
        # iterate through rows of M2
        for k in range(len(other)):
            matrixMultiply[i][j] += self[i][k] * other[k][j]
  return matrixMultiply

### **Test Code For Matrix Multiplication**

In [8]:
#Test Code - Matrix Multiplication Woeking
# 3x3 matrix
print("Test 1")
A = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
B = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

print(matrix_mult(A, B))
print(" ")
print('''Correct answer is: [114, 160, 60, 27]
                   [74, 97, 73, 14]
                   [119, 157, 112, 23]''')

#Test Code - 3x3 and 2x4 matrix
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 2x4 matrix
Y = [[6,7,3,0],
    [4,5,9,1]]
print(" ")
print("Test 2")
print(matrix_mult(X, Y))

Test 1
[[114. 160.  60.  27.]
 [ 74.  97.  73.  14.]
 [119. 157. 112.  23.]]
 
Correct answer is: [114, 160, 60, 27]
                   [74, 97, 73, 14]
                   [119, 157, 112, 23]
 
Test 2
Matrices cannot be multiplied.
None
