<a href="https://colab.research.google.com/github/MustafaKhan670093/ESC180-Intro-To-Computer-Programming/blob/master/Lab_7_Submission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mustafa's Submission For Lab 7: Guassian Elimination**

More information on lab [here](https://www.cs.toronto.edu/~guerzhoy/180/labs/lab07.pdf).

# **Problem 1**

Download numpy.py and understand how to print lists of lists as matrices by converting lists of lists to arrays (lines 1-11). Write a function `print_matrix(M_lol)` which prints the nested list M_lol as a matrix. You will be able to use your function to debug your implementation of Gaussian Elimination

In [ ]:
#Needed for array() and dot()
import numpy as np
from numpy import *


#Printing matrices using NumPy:

#Convert a list of lists into an array:
M_listoflists = [[1,-2,3],[3,10,1],[1,5,3]]
M = array(M_listoflists)
#Now print it:
#print(M)




#Compute M*x for matrix M and vector x by using
#dot. To do that, we need to obtain arrays
#M and x
M = array([[1,-2,3],[3,10,1],[1,5,3]])
x = array([75,10,-11])
b = dot(M,x)        

#print(M)
#[[ 1 -2  3]
# [ 3 10  1]
# [ 1  5  3]]

#To obtain a list of lists from the array M, we use .tolist()
#M_listoflists = M.tolist() 

#print(M_listoflists) #[[1, -2, 3], [3, 10, 1], [1, 5, 3]]

##############################################################

def print_matrix(M_lol):
  matrix = array(M_lol)
  print(matrix)

print_matrix(M_listoflists)


[[ 1 -2  3]
 [ 3 10  1]
 [ 1  5  3]]


## **Probelm 2**

Write a function with the signature `get_lead_ind(row)` which takes in a list of numbers row, and returns the index of the first non-zero element of row. The function should return `len(row)` if the row contains no non-zero elements.

In [ ]:
def get_lead_ind(row):
  #Check for first non-zero elements in row and return their index:
  for i in range(len(row)):
    if row[i] != 0:
      return i
  #After not finding any non-zero elements:
  return len(row)


#Test 1 - Index at 1
A = [0, 1, 2, 3]
print("Test 1, List A: " + str(A))
print("Non Zero Number @ Index: " + str(get_lead_ind(A)))
print(' ')
#Test 2 - Index at 0
B = [1, 0, 2, 3]
print("Test 2, List B: " + str(B))
print("Non Zero Number @ Index: " + str(get_lead_ind(B)))
print(' ')
#Test 3 - Return Length Of Row
C = [0, 0, 0, 0, 0]
print("Test 3, List B: " + str(C))
print("Length Of Row: " + str(get_lead_ind(C)))
print(' ')

Test 1, List A: [0, 1, 2, 3]
Non Zero Number @ Index: 1
 
Test 2, List B: [1, 0, 2, 3]
Non Zero Number @ Index: 0
 
Test 3, List B: [0, 0, 0, 0, 0]
Length Of Row: 5
 


# **Problem 3**

Write a function with the signature `get_row_to_swap(M, start_i)` which takes in a matrix M (represented as a list of lists) and an integer `start_i`, and returns the row that needs to be swapped (permuted/interchanged) with the row `M[start_i]`. The row that needs to be swapped with the row `M[start_i]` is the row at index larger or equal to `start_i` which has the leading non-zero coefficient that is as far to the left as possible.
For example, for
```
M = [[5, 6, 7, 8],
[0, 0, 0, 1],
[0, 0, 5, 2],
[0, 1, 0, 0]]

start_i = 1
```
`[0,0, 0, 1]` needs to be swapped with `[0, 1, 0, 0]`, so that the function should return 3.

In [ ]:
def get_row_to_swap(M, start_i):
  base_lead_index = get_lead_ind(M[start_i])
  lead_indexes = []
  #sorted_indexes = []
  count = 0

  for i in range(len(M)):
    lead_indexes.append(get_lead_ind(M[i]))

  max_i = start_i
  max_lead_index = lead_indexes[start_i]
  
  for i in range(len(lead_indexes)):              
    if i >= start_i:                             
      if lead_indexes[i] <= base_lead_index:         
        if lead_indexes[i] < max_lead_index:
          max_i = i
          max_lead_index = lead_indexes[i]
        elif lead_indexes[i] == max_lead_index: 
          count += 1
          if count <= 1:
            max_i = i
            max_lead_index = lead_indexes[i]    #Use min function to achieve same result

  return max_i

#Test 1
A = [[5, 6, 7, 8], 
     [0, 0, 0, 1], 
     [0, 0, 5, 2], 
     [0, 1, 0, 0]]
 
print(get_row_to_swap(A, 1))

#Test 2 - 
B = [[0, 0, 0, 1], 
     [5, 6, 7, 8], 
     [0, 0, 5, 2], 
     [0, 1, 0, 0]]

print(get_row_to_swap(B, 0))

#Test 3 - When row full of zeros
C = [[0, 0, 0, 1], 
     [5, 6, 7, 8], 
     [0, 0, 5, 2], 
     [0, 0, 0, 0]]

print(get_row_to_swap(C, 2))

#Test 4
D = [[5, 6, 7, 8],
     [0, 1, 0, 0],
     [0, 0, 0, 1],  
     [0, 0, 5, 2]]

print(get_row_to_swap(D, 2))

#Test 5
E = [[0, 0, 0, 1],
     [5, 6, 7, 8], 
     [0, 1, 0, 0],
     [0, 0, 5, 2]]
 
print(get_row_to_swap(E, 1))

#Test 6
F = [[ 0, 0, 1, 0, 2], 
     [ 1, 0, 2, 3, 4,], 
     [ 3, 0, 4, 2, 1,], 
     [ 1, 0, 1, 1, 2,]]
print(get_row_to_swap(F, 0))

3
1
2
3
1
1


## **Problem 4**
Write a function with the signature `add_rows_coefs(r1, c1, r2, c2)` which takes in rows (represented as lists of equal lengths) `r1` and `r2` and coefficients (floats) `c1` and `c2`, and returns a new list that contains the row `c1*r1 + c2r2`. (Note: to create a new list of 10 zeros, you can use `[0]*10`.)

In [ ]:
def add_rows_coefs(r1, c1, r2, c2):
  result = []
  for i in range(len(r1)):
    elem = c1*r1[i] + c2*r2[i]
    result.append(elem)                 #Note: np.array(r1)*c1 . In the end, return result.tolist() if using numpy.
  return result

## **Problem 5**

Write a function with the signature `eliminate(M, row_to_sub, best_lead_ind)` which takes in a matrix M (represented as a list of lists), `row_to_sub`, an index of the row to subtract from other rows to eliminate, and `best_lead_ind`, the index of the coefficient to be eliminated in rows below index `best_lead_ind`. Assume that M`[row_to_sub]` is all zeros before M[row_to_sub][best_lead_ind]

In [ ]:
def eliminate(M, row_to_sub, best_lead_ind):
  copy_row_to_sub = M[row_to_sub]
  temp_row = []
  for i in range((row_to_sub + 1), len(M)):
    coef = M[row_to_sub][get_lead_ind(M[row_to_sub])]
    # if coef != 1:
    temp_row = [j * (1/coef) for j in M[row_to_sub]]
    copy_row_to_sub = [j * M[i][best_lead_ind] for j in temp_row]
    M[i] = [x1 - x2 for (x1, x2) in zip(M[i], copy_row_to_sub)]
    copy_row_to_sub = M[row_to_sub]
    # else:
    #   copy_row_to_sub = [j * M[i][best_lead_ind] for j in M[row_to_sub]]
    #   M[i] = [x1 - x2 for (x1, x2) in zip(M[i], copy_row_to_sub)]
    #   copy_row_to_sub = M[row_to_sub]

A = [[ 1,  0,  2,  3,  4],
     [ 0,  0,  1,  0,  2],
     [ 0,  0,  0, -7, -7],
     [ 0,  0,  0, -2,  0]]

print(get_lead_ind(M[2])) #3
eliminate(A, 1, get_lead_ind(M[1]))
print(np.array(A))


# #Test  
# M = [[5, 6, 7, 8],
#      [0,0, 1, 1],
#      [0, 0, 5, 2],
#      [0, 0, 7, 0]]

# row_to_sub = 1
# best_lead_ind = 2

# eliminate(M, row_to_sub, best_lead_ind)
# print(np.array(M))

3
[[ 1.  0.  2.  3.  4.]
 [ 0.  0.  1.  0.  2.]
 [ 0.  0.  0. -7. -7.]
 [ 0.  0.  0. -2.  0.]]


## **Problem 6**

Write a function with the signature `forward_step(M)` which takes in an arbitrary matrix `M` (as a list of lists), applies the forward step of Gaussian Elimination to it, and modifies `M` to be the matrix obtained after the forward step is applied. This can be done by repeatedly calling `get_row_to_swap`, swapping rows, and calling `eliminate`. Unlike with ESC103, I recommend that you keep the entire matrix rather than extracting submatrices. The process of performing the forward step remains essentially the same. As you write `forward_step()`, add `print()` statements to `forward_step()` to produce output similar to the examples provided on this handout (i.e, print out the matrix transformation process, and comments on what’s happening at every step).

In [ ]:
def forward_step(M):
  print("The matrix is currently:")
  print(np.array(M))
  status = True
  temp = M
  count = 0
  #while status == True:
  for i in range(len(M)):
    print("Swapping rows " + str(i) + " and " + str(get_row_to_swap(M, i)) + " so that entry " + str(i) + " in the current row is non-zero.")
    M[get_row_to_swap(M, i)], M[i] = M[i], M[get_row_to_swap(M, i)]
    print("The matrix is currently:")
    print(np.array(M))
    print("Adding row " + str(i) + " to rows below it to eliminate coefficients in column " + str(get_row_to_swap(M, i)))
    print("The matrix is currently:")
    eliminate(M, i, get_lead_ind(M[i]))
    print(np.array(M))
    # count += 1
    # if temp == M:
    #   status = False
    # else:
    #   temp = M
  print("===========================")
  print("Done with the forward step.")
  print("The matrix is currently:")
  print(np.array(M))

#The matrix is currently:
M = [[ 0, 0, 1, 0, 2], 
     [ 1, 0, 2, 3, 4,], 
     [ 3, 0, 4, 2, 1,], 
     [ 1, 0, 1, 1, 2,]]

forward_step(M)

The matrix is currently:
[[0 0 1 0 2]
 [1 0 2 3 4]
 [3 0 4 2 1]
 [1 0 1 1 2]]
Swapping rows 0 and 1 so that entry 0 in the current row is non-zero.
The matrix is currently:
[[1 0 2 3 4]
 [0 0 1 0 2]
 [3 0 4 2 1]
 [1 0 1 1 2]]
Adding row 0 to rows below it to eliminate coefficients in column 0
The matrix is currently:
[[  1.   0.   2.   3.   4.]
 [  0.   0.   1.   0.   2.]
 [  0.   0.  -2.  -7. -11.]
 [  0.   0.  -1.  -2.  -2.]]
Swapping rows 1 and 1 so that entry 1 in the current row is non-zero.
The matrix is currently:
[[  1.   0.   2.   3.   4.]
 [  0.   0.   1.   0.   2.]
 [  0.   0.  -2.  -7. -11.]
 [  0.   0.  -1.  -2.  -2.]]
Adding row 1 to rows below it to eliminate coefficients in column 1
The matrix is currently:
[[ 1.  0.  2.  3.  4.]
 [ 0.  0.  1.  0.  2.]
 [ 0.  0.  0. -7. -7.]
 [ 0.  0.  0. -2.  0.]]
Swapping rows 2 and 2 so that entry 2 in the current row is non-zero.
The matrix is currently:
[[ 1.  0.  2.  3.  4.]
 [ 0.  0.  1.  0.  2.]
 [ 0.  0.  0. -7. -7.]
 [ 0.  0. 

## **Problem 7**

Write a function with the signature `backward_step(M)` which takes in an arbitrary matrix M and applies the backward step of Gaussian Elimination to it. 

In [ ]:
def backwards_eliminate(M, row_to_sub, best_lead_ind):
  copy_row_to_sub = M[row_to_sub]
  temp_row = []
  a_range = range(len(M))
  reversed_range = list(reversed(a_range))
  for i in a_range:
    if i < row_to_sub:
      coef = M[row_to_sub][get_lead_ind(M[row_to_sub])]
      if coef != 1:
        temp_row = [j * (1/coef) for j in M[row_to_sub]]
        copy_row_to_sub = [j * M[i][best_lead_ind] for j in temp_row]
        M[i] = [x1 - x2 for (x1, x2) in zip(M[i], copy_row_to_sub)]
        copy_row_to_sub = M[row_to_sub]
      else:
        copy_row_to_sub = [j * M[i][best_lead_ind] for j in M[row_to_sub]]
        M[i] = [x1 - x2 for (x1, x2) in zip(M[i], copy_row_to_sub)]
        copy_row_to_sub = M[row_to_sub]
    

def backward_step(M):
  print("The matrix is currently:")
  print(np.array(M))
  a_range = range(len(M))
  reversed_range = reversed(a_range)
  print("Now performing the backwards step.")
  for i in reversed_range:
    print("Adding row " + str(i) + " to rows above it to eliminate coefficients in column " + str(get_row_to_swap(M, i)))
    print("The matrix is currently:")
    backwards_eliminate(M, i, get_lead_ind(M[i]))
    print(np.array(M))
  print("Now dividing each row by the leading coefficient.")
  for i in range(len(M)):
    M[i] = [j * (1/M[i][get_lead_ind(M[i])]) for j in M[i]]
  print("The matrix is currently:")
  print(np.array(M))
  
M = [[ 1., -2., 3., 22. ],
     [ 0., 16., -8., 248. ],
     [ 0., 0., 3.5, -38.5]]

backward_step(M)


The matrix is currently:
[[  1.   -2.    3.   22. ]
 [  0.   16.   -8.  248. ]
 [  0.    0.    3.5 -38.5]]
Now performing the backwards step.
Adding row 2 to rows above it to eliminate coefficients in column 2
The matrix is currently:
[[  1.   -2.    0.   55. ]
 [  0.   16.    0.  160. ]
 [  0.    0.    3.5 -38.5]]
Adding row 1 to rows above it to eliminate coefficients in column 1
The matrix is currently:
[[  1.    0.    0.   75. ]
 [  0.   16.    0.  160. ]
 [  0.    0.    3.5 -38.5]]
Adding row 0 to rows above it to eliminate coefficients in column 0
The matrix is currently:
[[  1.    0.    0.   75. ]
 [  0.   16.    0.  160. ]
 [  0.    0.    3.5 -38.5]]
Now dividing each row by the leading coefficient.
The matrix is currently:
[[  1.   0.   0.  75.]
 [  0.   1.   0.  10.]
 [  0.   0.   1. -11.]]


## **Problem 8.**
Now, write a function that solves the equation `Mx = b` for the vector `x`. The idea is to first build the augmented matrix (M|b), then apply Gaussian Elimination to the augmented matrix, and then solve for x. Test your solve() function. In numpy.py, we provide code to quickly perform matrix multiplication in Python so that you can pick arbitrary M and x, obtain a b by multiplying M and x, and then verify that your algorithm can recover the x.

In [ ]:
def gaussian_elimination(M, b):
  A = M  #Augmented matrix
  new_b = []
  for i in range(len(b)):
    A[i].append(b[i])
  forward_step(A)
  backward_step(A)
  print(' ')
  X = [row[-1] for row in A]
  print("Solution (X vector) = " + str(X))

#Test
M = [[ 0, 0, 1, 0], 
     [ 1, 0, 2, 3], 
     [ 3, 0, 4, 2], 
     [ 1, 0, 1, 1]]

b = [2, 4, 1, 2]

gaussian_elimination(M, b)

The matrix is currently:
[[0 0 1 0 2]
 [1 0 2 3 4]
 [3 0 4 2 1]
 [1 0 1 1 2]]
Swapping rows 0 and 1 so that entry 0 in the current row is non-zero.
The matrix is currently:
[[1 0 2 3 4]
 [0 0 1 0 2]
 [3 0 4 2 1]
 [1 0 1 1 2]]
Adding row 0 to rows below it to eliminate coefficients in column 0
The matrix is currently:
[[  1   0   2   3   4]
 [  0   0   1   0   2]
 [  0   0  -2  -7 -11]
 [  0   0  -1  -2  -2]]
Swapping rows 1 and 1 so that entry 1 in the current row is non-zero.
The matrix is currently:
[[  1   0   2   3   4]
 [  0   0   1   0   2]
 [  0   0  -2  -7 -11]
 [  0   0  -1  -2  -2]]
Adding row 1 to rows below it to eliminate coefficients in column 1
The matrix is currently:
[[ 1  0  2  3  4]
 [ 0  0  1  0  2]
 [ 0  0  0 -7 -7]
 [ 0  0  0 -2  0]]
Swapping rows 2 and 2 so that entry 2 in the current row is non-zero.
The matrix is currently:
[[ 1  0  2  3  4]
 [ 0  0  1  0  2]
 [ 0  0  0 -7 -7]
 [ 0  0  0 -2  0]]
Adding row 2 to rows below it to eliminate coefficients in column 